# Generated by Django 3.2.11 on 2022-02-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(verbose_name='班级(期)')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('start_date', models.DateTimeField(verbose_name='开始日期')),
                ('graduate_date', models.DateTimeField(blank=True, null=True, verbose_name='结课日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.userinfo', verbose_name='班主任')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.school', verbose_name='校区')),
                ('tech_teacher', models.ManyToManyField(blank=True, null=True, related_name='tech_classes', to='web.UserInfo', verbose_name='任课老师')),
            ],
        ),
    ]
