# Generated by Django 3.2.11 on 2022-02-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_classlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateField(blank=True, null=True, verbose_name='结课日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='start_date',
            field=models.DateField(verbose_name='开始日期'),
        ),
    ]
