# Generated by Django 3.0.5 on 2022-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220331_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结课日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='start_date',
            field=models.DateTimeField(verbose_name='开始日期'),
        ),
    ]
