# Generated by Django 3.0.5 on 2022-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20220331_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateField(blank=True, null=True, verbose_name='结课日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='start_date',
            field=models.DateField(verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='跟进日期'),
        ),
    ]
