# Generated by Django 3.0.5 on 2022-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20220403_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
